REM python model_simple_unet.py --model_name unet_batchnorm --epochs 240 --learning_rate 3e-7 --dataset hue_shifted_images --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 2 --gradient_accumulation_steps 4 --epochs_per_save 10 --use_batch_norm
REM python model_simple_unet.py --model_name unet_height_4_small --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-5 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --use_res_conv --unet_attention --hidden_channels 32 --pyramid_height 4
REM python model_simple_unet.py --model_name unet_height_4_small_continue --epochs 400 --rotation_augmentation --background_weights_split --learning_rate 1e-6 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --use_res_conv --unet_attention --hidden_channels 32 --pyramid_height 4 --prev_model_ckpt unet_height_4_small

REM python model_simple_unet.py --model_name unet_plus_plus_height_4_small --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-5 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 32 --pyramid_height 4 --unet_plus deep_supervision
REM python model_simple_unet.py --model_name unet_plus_plus_height_4_small_continue --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-6 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 32 --pyramid_height 4 --unet_plus deep_supervision --prev_model_ckpt unet_plus_plus_height_4_small

REM python model_simple_unet.py --model_name unet_plus_plus_height_4_small_elastic --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-5 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 32 --pyramid_height 4 --unet_plus deep_supervision
REM python model_simple_unet.py --model_name unet_plus_plus_height_4_small_elastic_continue --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-6 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 32 --pyramid_height 4 --unet_plus deep_supervision --prev_model_ckpt unet_plus_plus_height_4_small_elastic

REM python model_simple_unet.py --model_name unet_plus_plus_height_6_small_elastic --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-5 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 16 --pyramid_height 6 --unet_plus deep_supervision
REM python model_simple_unet.py --model_name unet_plus_plus_height_6_small_elastic_continue --epochs 240 --rotation_augmentation --background_weights_split --learning_rate 1e-6 --dataset hdf5_copy --train_subdata dataset1_split1 --val_subdata dataset1_split2 --batch_size 1 --gradient_accumulation_steps 1 --epochs_per_save 10 --use_batch_norm --hidden_channels 16 --pyramid_height 6 --unet_plus deep_supervision --prev_model_ckpt unet_plus_plus_height_6_small_elastic

unet_plus_plus_height_5